[workspace]
members = [
    "engine",
    "booktool",
    "tune8db",
    "scrzebra",
    "practice",
    "enddev",
    "wasm-simple",
    "engine/bitboard",
    "engine/pcstat",
    "engine/epcstat",
    "engine/bitbcnt"
]

[package]
name = "c2rust_out"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2018"
autobins = false

[profile.release]
opt-level = 3
lto = "fat" 

[profile.dev]
opt-level = 0
lto="thin"

[lib]
name = "c2rust_out"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]


[[bin]]
path = "src/main.rs"
name = "zebra"

[dependencies]
libc = "0.2"
engine = { path= "./engine" }

[build-dependencies]
pkg-config = "0.3.16"

