[workspace]
members = [
    "engine",
    "booktool",
    "tune8db",
    "scrzebra",
    "practice",
    "enddev",
    "wasm-simple",
    "engine/bitboard",
    "engine/pcstat",
    "engine/epcstat",
    "engine/bitbcnt",
    "libc-wrapper",
    "engine/engine-traits"
]

[package]
name = "c2rust_out"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2018"
autobins = false

[profile.release]
opt-level = 3
lto = "fat" 

[profile.dev]
opt-level = 0
lto="thin"

[lib]
name = "c2rust_out"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]


[[bin]]
path = "src/main.rs"
name = "zebra"

[dependencies]
engine = { path = "./engine" }
libc-wrapper = { path = "./libc-wrapper" }
flate2 = "1.0"
engine-traits = { path = "./engine/engine-traits" }

[build-dependencies]
pkg-config = "0.3.16"

