[workspace]
members = [
    "tests",
    "webzebra/crate",
    "crates/*"
]
exclude = ["crates/script"]

[profile.release]
opt-level = 3
lto = "thin"
overflow-checks = true
incremental=true
debug=false

[profile.dev]
opt-level = 0
lto=false
