name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly-2022-02-16
          override: true
          profile: minimal
          components: llvm-tools-preview

    - uses: Swatinem/rust-cache@v1

    - uses: actions-rs/install@v0.1
      with:
          crate: cargo-binutils
          version: latest

    - name: Install Wasm Pack
      uses: actions-rs/install@v0.1
      with:
          crate: wasm-pack
          version: 0.10.2

    - name: Build and run tests
      run: bash ./run-tests.sh

    - name: Build Rust WebZebra crate
      working-directory: ./webzebra/crate
      run: wasm-pack build --target web --release
