name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly-2022-02-16
          override: true
          profile: minimal
          components: llvm-tools-preview

    - uses: Swatinem/rust-cache@v1

    - uses: actions-rs/install@v0.1
      with:
          crate: cargo-binutils
          version: latest

    - name: Build and run tests
      run: bash ./run-tests.sh
