name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: webzebra/yarn.lock

    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly-2022-02-16
          override: true
          profile: minimal
          components: llvm-tools-preview

    - name: Cache cargo files
      uses: actions/cache@v2
      with:
          path: |
            ~/.cargo/bin
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            ./target
            ./test-target
          key: ${{ runner.os }}-cargo-files-0 # todo better key - this one is never invalidated so the cache goes slowly out of date

    - name: Install Binutils
      run: cargo install cargo-binutils || cargo install cargo-binutils --force

    - name: Install Wasm Pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Build and run tests
      env:
        CARGO_INCREMENTAL: 0
      run: bash ./run-tests.sh

    - name: Build Rust WebZebra crate
      working-directory: ./webzebra/crate
      env:
        CARGO_INCREMENTAL: 0
      run: wasm-pack build --target web --release

    - name: Install yarn Deps
      working-directory: ./webzebra
      run: yarn

    - name: Build WebZebra
      working-directory: ./webzebra
      run: yarn vite build

    - name: Package dist directory
      working-directory: ./webzebra/dist
      run: zip -r ../dist.zip .

    - name: Deploy Webzebra
      if: github.ref == 'refs/heads/master'
      working-directory: ./webzebra
      env:
        NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
      run: |
        curl -H "Content-Type: application/zip" \
             -H "Authorization: Bearer ${NETLIFY_ACCESS_TOKEN}" \
             --data-binary "@dist.zip" \
             https://api.netlify.com/api/v1/sites/webzebra.netlify.app/deploys \
             --fail \
             -o /dev/null \
             --show-error
