name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: webzebra/yarn.lock

    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly-2022-02-16
          override: true
          profile: minimal
          components: llvm-tools-preview

    - name: Cache cargo binaries
      uses: actions/cache@v1
      with:
          path: |
            ~/.cargo/bin
            ~/.cargo/.crates*
          key: ${{ runner.os }}-cargo-binaries-1

    - name: Install Binutils
      run: cargo install cargo-binutils || cargo install cargo-binutils --force

    - name: Install Wasm Pack
      run: cargo install wasm-pack || cargo install wasm-pack --force

    - name: Cache Rust Dependencies
      uses: Swatinem/rust-cache@v1

    - name: Build and run tests
      run: bash ./run-tests.sh

    - name: Build Rust WebZebra crate
      working-directory: ./webzebra/crate
      run: wasm-pack build --target web --release

    - name: Install yarn Deps
      working-directory: ./webzebra
      run: yarn

    - name: Build WebZebra
      working-directory: ./webzebra
      run: yarn vite build

    - name: Package dist directory
      working-directory: ./webzebra/dist
      run: zip -r ../dist.zip .

    - name: Deploy Webzebra
#      if: github.ref == 'ref/head/master' // todo uncomment
      run: |
        curl -H "Content-Type: application/zip" \
             -H "Authorization: Bearer ${NETLIFY_ACCESS_TOKEN}" \
             --data-binary "@dist.zip" \
             https://api.netlify.com/api/v1/sites/webzebra.netlify.app/deploys
